language: c++

matrix:
  include:
    - os: osx
      compiler: clang
      env: OPJ_CI_ARCH=x86_64 OPJ_CI_BUILD_CONFIGURATION=Release
      compiler: clang-3.9
      env: OPJ_CI_ARCH=x86_64 OPJ_CI_BUILD_CONFIGURATION=Release
      sudo: true
    - os: linux

install:
  - ./tools/travis-ci/install.sh

script:
  - ./tools/travis-ci/run.sh
  - ./tools/travis-ci/abi-check.sh
