language: cpp

matrix:
  include:
    - os: osx
      compiler: clang
      env: GROK_CI_ARCH=x86_64 GROK_CI_BUILD_CONFIGURATION=Release GROK_CI_INCLUDE_IF_DEPLOY=1
    - os: linux
      dist: trusty
      sudo: required
      compiler: g++
      env: GROK_CI_ARCH=x86_64 GROK_CI_BUILD_CONFIGURATION=Release GROK_CI_INCLUDE_IF_DEPLOY=1 GROK_NONCOMMERCIAL=1
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5

install:
  - ./tools/travis-ci/install.sh

script:
  - ./tools/travis-ci/run.sh

before_deploy:
  - export GROK_RELEASE_PKG_FILE=$(ls build/openjpeg-${TRAVIS_TAG}*)
  - echo "deploying $GROK_RELEASE_PKG_FILE to GitHub releases"

deploy:
  provider: releases
  api_key:
    secure: Npi13uOffALCVNwea4p4q8v85Lo/WsRqaeZQcWrAkt8MxRnfvWQtmnuwmHnVB6Cig+T1lVUHrklOaJIApIb6nkGq3CS/9bD8+SCS2NEdAAP/QYWnBi0ubWXVMRyDLypmwRpzLNSZ0xLYGFUl2PjieZYKRcz1dd/J7S+FnXhPtdjXweq0FS63zTcMe7ggjfmzSOWUCEFmMjZPaM0Be+3PweieCO1dxlHuy7ugCkx2S7d+5hNsicIhQmTADjqtJAkHoMhYqu6/yLFxhjO/+f938PATFULdODTvjCsUwdN/ySWi1Oj4uPAntfytZP7H6YrzLh8dS73QCsdkhhDJIgJskHIBSbRyyEVUnOvQgD9VaBVGHtc1KtZQTwc41OUO3BGPHl97s3oX6bqWqo/L53dB3TPHGx+1+2HL/F0zaDZuHhAKMkPwe8LFPMPB/ur65zXMHjnWb2ZTVVdoIvkbQ7nu8ApI60ejxocYBsEyAuC2CPXU2ki4jdEhm0E1hIziWNE9/LTuM17ziQuJ6WpXOSMrfP4o5aVDmLp5ZGBSocrspOksgyI9XogHaO/r+Y6N3exy+giObFfMHkZVUpsKrKmtOJ7TC1Vg5HsYGlWW8RN8dkJV47bUXm9K4sMos9eYMUt/czykPAs+132cogpII3QxXpFZQqZg6SEPVfOiyqQzTUI=
  file_glob: true
  file: "${GROK_RELEASE_PKG_FILE}"
  skip_cleanup: true
  on:
    repo: GrokImageCompression/grok
    tags: true
    condition: "$GROK_CI_INCLUDE_IF_DEPLOY = 1"

