version: 2.1.1.{build}
branches:
  except:
  - coverity_scan
skip_tags: true
clone_depth: 50
environment:
  matrix:
  - GROK_CI_ARCH: x86
    GROK_CI_VSCOMNTOOLS: $(VS140COMNTOOLS)
  - GROK_CI_ARCH: x64
    GROK_CI_VSCOMNTOOLS: $(VS140COMNTOOLS)
install:
- cmd: c:\cygwin\bin\bash ./tools/travis-ci/install.sh
build_script:
- cmd: >-
    "%GROK_CI_VSCOMNTOOLS%..\..\VC\vcvarsall.bat" %GROK_CI_ARCH%

    bash ./tools/travis-ci/run.sh
test: off
deploy: off
